id: spark-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: spark
    containers:
      - name: spark
        image: jayunit100/spark7
        command:
           - /bin/bash
           - /opt/run.sh
           - master
        cpu: 1000
        ports:
          - name: spark-master
            containerPort: 7077
labels:
  name: spark-master

