#  Master pod definition.        # 
id: spark-master                 # This ID will be referenced in the service defs.  
                                 # Those services, when launched, make this pods state highly available.
                                 #
kind: Pod                        # KIND: We are defining a POD in this file.
apiVersion: v1beta1              # DESIREDSTATE: The containers and there run commands, ports, and so on.
desiredState:                    # From here on, we define what containers are actually part of this pod.
  manifest:                      # 
    version: v1beta1             #
    id: spark                    # 
    containers:                  # From here on out, you define the running containers...
      - name: spark              #  
      image: jayunit100/spark7   # IMAGE: The docker image to pull.  
      command:                   # COMMAND: Same as docker CMD.
           - /bin/bash           # COMMAND ARGUMENTS: When running a command in kubernetes, you need to provide 
           - /opt/run.sh         # separated arguments in a YAML list.  Similarly you separate params in Json.
           - master              #
      cpu: 1000                  # CPU: This is a relative value.
        ports:                   #
          - name: spark-master   # 
        containerPort: 7077      # CONTAINERPORT: is equivalent to docker's -p flag, it exposes
labels:                          # a port externally.
name: spark-master               # LABEL NAME: This label must match the selector which is defined in the 
                                 # corresponding service file.
