id: dbc
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: dbc
  # This is identical to the pod config above
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: dbc
        containers:
          - name: dbc
            image: "rhel7/dbc" #<-- needs to be built
            cpu: 1000
            ports:
              - name: webport
                containerPort: 80
    labels:
      name: dbc
